# Generated by Django 6.0.1 on 2026-02-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_availability'),
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='availability',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='consultants.consultantavailability'),
            preserve_default=False,
        ),
    ]
